### ISSUE TITLE
The "superCtor.prototype" property must be of type object. Received undefined

### ISSUE THREAD

**Issue by renejesusgv** [ibrod83/nodejs-web-scraper#19]
Hi everyone, Im getting **TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type object. Received undefined** even running your [runkit]( https://npm.runkit.com/nodejs-web-scraper)
These are the logs: 

```
util.js:160
    throw new ERR_INVALID_ARG_TYPE('superCtor.prototype',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor.prototype" property must be of type object. Received undefined
    at Object.inherits (util.js:160:11)
    at Object.exports.wrap (/home/rene/Documents/Own/Personal/web-scrapper/node_modules/cheerio-advanced-selectors/index.js:20:8)
    at Object.<anonymous> (/home/rene/Documents/Own/Personal/web-scrapper/node_modules/nodejs-web-scraper/operations/CollectContent.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/rene/Documents/Own/Personal/web-scrapper/node_modules/nodejs-web-scraper/index.js:1:24) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by ibrod83** [comment]
Can you show the code you're using..?

**Comment by ibrod83** [comment]
Thank you for pointing this out. It seems there was a compatibility issue with latest node versions. Fixed.
